Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = 'node1.172.24.0.11.nip.io'
  config.vm.network "private_network", ip: "172.24.0.11"
  config.vm.provider "virtualbox" do |v|
     v.memory = 4096
     v.cpus = 2
  end
  config.vm.provision "shell", inline: $script
end

$script = <<SCRIPT
  yum -y -q install httpd
  setenforce 0
  sed -i 's/enforcing/permissive/g' /etc/sysconfig/selinux
  mkdir -p /home/vagrant/sigstore/li9demo
  chown -R vagrant:vagrant /home/vagrant/sigstore
  chmod o+X /home/vagrant/
  ln -sf /home/vagrant/sigstore/ /var/www/html
  rm /etc/httpd/conf.d/welcome.conf
  systemctl start httpd
SCRIPT
